// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type CustomerPortalLicenseKeysValidateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ValidatedLicenseKey *components.ValidatedLicenseKey
}

func (o *CustomerPortalLicenseKeysValidateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CustomerPortalLicenseKeysValidateResponse) GetValidatedLicenseKey() *components.ValidatedLicenseKey {
	if o == nil {
		return nil
	}
	return o.ValidatedLicenseKey
}
