// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AdvertisementSortProperty string

const (
	AdvertisementSortPropertyCreatedAt      AdvertisementSortProperty = "created_at"
	AdvertisementSortPropertyMinusCreatedAt AdvertisementSortProperty = "-created_at"
	AdvertisementSortPropertyGrantedAt      AdvertisementSortProperty = "granted_at"
	AdvertisementSortPropertyMinusGrantedAt AdvertisementSortProperty = "-granted_at"
	AdvertisementSortPropertyViews          AdvertisementSortProperty = "views"
	AdvertisementSortPropertyMinusViews     AdvertisementSortProperty = "-views"
	AdvertisementSortPropertyClicks         AdvertisementSortProperty = "clicks"
	AdvertisementSortPropertyMinusClicks    AdvertisementSortProperty = "-clicks"
)

func (e AdvertisementSortProperty) ToPointer() *AdvertisementSortProperty {
	return &e
}
func (e *AdvertisementSortProperty) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "granted_at":
		fallthrough
	case "-granted_at":
		fallthrough
	case "views":
		fallthrough
	case "-views":
		fallthrough
	case "clicks":
		fallthrough
	case "-clicks":
		*e = AdvertisementSortProperty(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdvertisementSortProperty: %v", v)
	}
}
