// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdvertisementCampaignListResource struct {
	Items      []AdvertisementCampaign `json:"items"`
	Pagination Pagination              `json:"pagination"`
	// The dimensions (width, height) in pixels of the advertisement images.
	Dimensions []int64 `json:"dimensions"`
}

func (o *AdvertisementCampaignListResource) GetItems() []AdvertisementCampaign {
	if o == nil {
		return []AdvertisementCampaign{}
	}
	return o.Items
}

func (o *AdvertisementCampaignListResource) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}

func (o *AdvertisementCampaignListResource) GetDimensions() []int64 {
	if o == nil {
		return []int64{}
	}
	return o.Dimensions
}
