// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AttachedCustomFieldCreate - Schema to attach a custom field to a resource.
type AttachedCustomFieldCreate struct {
	// ID of the custom field to attach.
	CustomFieldID string `json:"custom_field_id"`
	// Whether the value is required for this custom field.
	Required bool `json:"required"`
}

func (o *AttachedCustomFieldCreate) GetCustomFieldID() string {
	if o == nil {
		return ""
	}
	return o.CustomFieldID
}

func (o *AttachedCustomFieldCreate) GetRequired() bool {
	if o == nil {
		return false
	}
	return o.Required
}
