// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthorizeOrganization struct {
	ID        string  `json:"id"`
	Slug      string  `json:"slug"`
	AvatarURL *string `json:"avatar_url"`
}

func (o *AuthorizeOrganization) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AuthorizeOrganization) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *AuthorizeOrganization) GetAvatarURL() *string {
	if o == nil {
		return nil
	}
	return o.AvatarURL
}
