// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthorizeUser struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	AvatarURL *string `json:"avatar_url"`
}

func (o *AuthorizeUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AuthorizeUser) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *AuthorizeUser) GetAvatarURL() *string {
	if o == nil {
		return nil
	}
	return o.AvatarURL
}
