// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Author struct {
	ID        int64  `json:"id"`
	Login     string `json:"login"`
	HTMLURL   string `json:"html_url"`
	AvatarURL string `json:"avatar_url"`
}

func (o *Author) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Author) GetLogin() string {
	if o == nil {
		return ""
	}
	return o.Login
}

func (o *Author) GetHTMLURL() string {
	if o == nil {
		return ""
	}
	return o.HTMLURL
}

func (o *Author) GetAvatarURL() string {
	if o == nil {
		return ""
	}
	return o.AvatarURL
}
