// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitGrantLicenseKeysProperties struct {
	LicenseKeyID *string `json:"license_key_id,omitempty"`
	DisplayKey   *string `json:"display_key,omitempty"`
}

func (o *BenefitGrantLicenseKeysProperties) GetLicenseKeyID() *string {
	if o == nil {
		return nil
	}
	return o.LicenseKeyID
}

func (o *BenefitGrantLicenseKeysProperties) GetDisplayKey() *string {
	if o == nil {
		return nil
	}
	return o.DisplayKey
}
