// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BenefitCustomProperties - Properties for a benefit of type `custom`.
type BenefitCustomProperties struct {
	Note *string `json:"note"`
}

func (o *BenefitCustomProperties) GetNote() *string {
	if o == nil {
		return nil
	}
	return o.Note
}
