// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitGrantAdsProperties struct {
	AdvertisementCampaignID string `json:"advertisement_campaign_id"`
}

func (o *BenefitGrantAdsProperties) GetAdvertisementCampaignID() string {
	if o == nil {
		return ""
	}
	return o.AdvertisementCampaignID
}
