// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BenefitCustomSubscriberProperties - Properties available to subscribers for a benefit of type `custom`.
type BenefitCustomSubscriberProperties struct {
	Note *string `json:"note"`
}

func (o *BenefitCustomSubscriberProperties) GetNote() *string {
	if o == nil {
		return nil
	}
	return o.Note
}
