// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitDownloadablesProperties struct {
	Archived map[string]bool `json:"archived"`
	Files    []string        `json:"files"`
}

func (o *BenefitDownloadablesProperties) GetArchived() map[string]bool {
	if o == nil {
		return map[string]bool{}
	}
	return o.Archived
}

func (o *BenefitDownloadablesProperties) GetFiles() []string {
	if o == nil {
		return []string{}
	}
	return o.Files
}
