// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitLicenseKeysProperties struct {
	Prefix      *string                                `json:"prefix"`
	Expires     *BenefitLicenseKeyExpirationProperties `json:"expires"`
	Activations *BenefitLicenseKeyActivationProperties `json:"activations"`
	LimitUsage  *int64                                 `json:"limit_usage"`
}

func (o *BenefitLicenseKeysProperties) GetPrefix() *string {
	if o == nil {
		return nil
	}
	return o.Prefix
}

func (o *BenefitLicenseKeysProperties) GetExpires() *BenefitLicenseKeyExpirationProperties {
	if o == nil {
		return nil
	}
	return o.Expires
}

func (o *BenefitLicenseKeysProperties) GetActivations() *BenefitLicenseKeyActivationProperties {
	if o == nil {
		return nil
	}
	return o.Activations
}

func (o *BenefitLicenseKeysProperties) GetLimitUsage() *int64 {
	if o == nil {
		return nil
	}
	return o.LimitUsage
}
