// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitGrantDownloadablesProperties struct {
	Files []string `json:"files,omitempty"`
}

func (o *BenefitGrantDownloadablesProperties) GetFiles() []string {
	if o == nil {
		return nil
	}
	return o.Files
}
