// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitDownloadablesSubscriberProperties struct {
	ActiveFiles []string `json:"active_files"`
}

func (o *BenefitDownloadablesSubscriberProperties) GetActiveFiles() []string {
	if o == nil {
		return []string{}
	}
	return o.ActiveFiles
}
