// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BenefitDiscordCreateProperties - Properties to create a benefit of type `discord`.
type BenefitDiscordCreateProperties struct {
	GuildToken string `json:"guild_token"`
	// The ID of the Discord role to grant.
	RoleID string `json:"role_id"`
}

func (o *BenefitDiscordCreateProperties) GetGuildToken() string {
	if o == nil {
		return ""
	}
	return o.GuildToken
}

func (o *BenefitDiscordCreateProperties) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}
