// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BenefitCustomCreateProperties - Properties for creating a benefit of type `custom`.
type BenefitCustomCreateProperties struct {
	Note *string `json:"note,omitempty"`
}

func (o *BenefitCustomCreateProperties) GetNote() *string {
	if o == nil {
		return nil
	}
	return o.Note
}
