// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitLicenseKeysCreateProperties struct {
	Prefix      *string                                `json:"prefix,omitempty"`
	Expires     *BenefitLicenseKeyExpirationProperties `json:"expires,omitempty"`
	Activations *BenefitLicenseKeyActivationProperties `json:"activations,omitempty"`
	LimitUsage  *int64                                 `json:"limit_usage,omitempty"`
}

func (o *BenefitLicenseKeysCreateProperties) GetPrefix() *string {
	if o == nil {
		return nil
	}
	return o.Prefix
}

func (o *BenefitLicenseKeysCreateProperties) GetExpires() *BenefitLicenseKeyExpirationProperties {
	if o == nil {
		return nil
	}
	return o.Expires
}

func (o *BenefitLicenseKeysCreateProperties) GetActivations() *BenefitLicenseKeyActivationProperties {
	if o == nil {
		return nil
	}
	return o.Activations
}

func (o *BenefitLicenseKeysCreateProperties) GetLimitUsage() *int64 {
	if o == nil {
		return nil
	}
	return o.LimitUsage
}
