// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitDownloadablesCreateProperties struct {
	Archived map[string]bool `json:"archived,omitempty"`
	Files    []string        `json:"files"`
}

func (o *BenefitDownloadablesCreateProperties) GetArchived() map[string]bool {
	if o == nil {
		return nil
	}
	return o.Archived
}

func (o *BenefitDownloadablesCreateProperties) GetFiles() []string {
	if o == nil {
		return []string{}
	}
	return o.Files
}
