// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BenefitDiscordSubscriberProperties - Properties available to subscribers for a benefit of type `discord`.
type BenefitDiscordSubscriberProperties struct {
	// The ID of the Discord server.
	GuildID string `json:"guild_id"`
}

func (o *BenefitDiscordSubscriberProperties) GetGuildID() string {
	if o == nil {
		return ""
	}
	return o.GuildID
}
