// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitGrantDiscordProperties struct {
	AccountID *string `json:"account_id,omitempty"`
	GuildID   *string `json:"guild_id,omitempty"`
	RoleID    *string `json:"role_id,omitempty"`
}

func (o *BenefitGrantDiscordProperties) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *BenefitGrantDiscordProperties) GetGuildID() *string {
	if o == nil {
		return nil
	}
	return o.GuildID
}

func (o *BenefitGrantDiscordProperties) GetRoleID() *string {
	if o == nil {
		return nil
	}
	return o.RoleID
}
