// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BenefitGitHubRepositorySubscriberProperties - Properties available to subscribers for a benefit of type `github_repository`.
type BenefitGitHubRepositorySubscriberProperties struct {
	// The owner of the repository.
	RepositoryOwner string `json:"repository_owner"`
	// The name of the repository.
	RepositoryName string `json:"repository_name"`
}

func (o *BenefitGitHubRepositorySubscriberProperties) GetRepositoryOwner() string {
	if o == nil {
		return ""
	}
	return o.RepositoryOwner
}

func (o *BenefitGitHubRepositorySubscriberProperties) GetRepositoryName() string {
	if o == nil {
		return ""
	}
	return o.RepositoryName
}
