// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CheckoutDiscountPercentageRepeatDuration - Schema for a percentage discount that is applied on every invoice
// for a certain number of months.
type CheckoutDiscountPercentageRepeatDuration struct {
	Duration         DiscountDuration `json:"duration"`
	DurationInMonths int64            `json:"duration_in_months"`
	Type             DiscountType     `json:"type"`
	BasisPoints      int64            `json:"basis_points"`
	// The ID of the object.
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Code *string `json:"code"`
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetDuration() DiscountDuration {
	if o == nil {
		return DiscountDuration("")
	}
	return o.Duration
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetDurationInMonths() int64 {
	if o == nil {
		return 0
	}
	return o.DurationInMonths
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetType() DiscountType {
	if o == nil {
		return DiscountType("")
	}
	return o.Type
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetBasisPoints() int64 {
	if o == nil {
		return 0
	}
	return o.BasisPoints
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CheckoutDiscountPercentageRepeatDuration) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}
