// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CheckoutConfirmStripeCustomFieldData struct {
}

// CheckoutConfirmStripe - Confirm a checkout session using a Stripe confirmation token.
type CheckoutConfirmStripe struct {
	// Key-value object storing custom field values.
	CustomFieldData *CheckoutConfirmStripeCustomFieldData `json:"custom_field_data,omitempty"`
	// ID of the product price to checkout. Must correspond to a price linked to the same product.
	ProductPriceID         *string  `json:"product_price_id,omitempty"`
	Amount                 *int64   `json:"amount,omitempty"`
	CustomerName           *string  `json:"customer_name,omitempty"`
	CustomerEmail          *string  `json:"customer_email,omitempty"`
	CustomerBillingAddress *Address `json:"customer_billing_address,omitempty"`
	CustomerTaxID          *string  `json:"customer_tax_id,omitempty"`
	// Discount code to apply to the checkout.
	DiscountCode *string `json:"discount_code,omitempty"`
	// ID of the Stripe confirmation token. Required for fixed prices and custom prices.
	ConfirmationTokenID *string `json:"confirmation_token_id,omitempty"`
}

func (o *CheckoutConfirmStripe) GetCustomFieldData() *CheckoutConfirmStripeCustomFieldData {
	if o == nil {
		return nil
	}
	return o.CustomFieldData
}

func (o *CheckoutConfirmStripe) GetProductPriceID() *string {
	if o == nil {
		return nil
	}
	return o.ProductPriceID
}

func (o *CheckoutConfirmStripe) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CheckoutConfirmStripe) GetCustomerName() *string {
	if o == nil {
		return nil
	}
	return o.CustomerName
}

func (o *CheckoutConfirmStripe) GetCustomerEmail() *string {
	if o == nil {
		return nil
	}
	return o.CustomerEmail
}

func (o *CheckoutConfirmStripe) GetCustomerBillingAddress() *Address {
	if o == nil {
		return nil
	}
	return o.CustomerBillingAddress
}

func (o *CheckoutConfirmStripe) GetCustomerTaxID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerTaxID
}

func (o *CheckoutConfirmStripe) GetDiscountCode() *string {
	if o == nil {
		return nil
	}
	return o.DiscountCode
}

func (o *CheckoutConfirmStripe) GetConfirmationTokenID() *string {
	if o == nil {
		return nil
	}
	return o.ConfirmationTokenID
}
