// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CheckoutLegacy - A checkout session.
type CheckoutLegacy struct {
	// The ID of the checkout.
	ID string `json:"id"`
	// URL the customer should be redirected to complete the purchase.
	URL           *string `json:"url,omitempty"`
	CustomerEmail *string `json:"customer_email"`
	CustomerName  *string `json:"customer_name"`
	// Product data for a checkout session.
	Product      CheckoutProduct `json:"product"`
	ProductPrice ProductPrice    `json:"product_price"`
}

func (o *CheckoutLegacy) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CheckoutLegacy) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *CheckoutLegacy) GetCustomerEmail() *string {
	if o == nil {
		return nil
	}
	return o.CustomerEmail
}

func (o *CheckoutLegacy) GetCustomerName() *string {
	if o == nil {
		return nil
	}
	return o.CustomerName
}

func (o *CheckoutLegacy) GetProduct() CheckoutProduct {
	if o == nil {
		return CheckoutProduct{}
	}
	return o.Product
}

func (o *CheckoutLegacy) GetProductPrice() ProductPrice {
	if o == nil {
		return ProductPrice{}
	}
	return o.ProductPrice
}
