// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CheckoutDiscountFixedRepeatDuration - Schema for a fixed amount discount that is applied on every invoice
// for a certain number of months.
type CheckoutDiscountFixedRepeatDuration struct {
	Duration         DiscountDuration `json:"duration"`
	DurationInMonths int64            `json:"duration_in_months"`
	Type             DiscountType     `json:"type"`
	Amount           int64            `json:"amount"`
	Currency         string           `json:"currency"`
	// The ID of the object.
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Code *string `json:"code"`
}

func (o *CheckoutDiscountFixedRepeatDuration) GetDuration() DiscountDuration {
	if o == nil {
		return DiscountDuration("")
	}
	return o.Duration
}

func (o *CheckoutDiscountFixedRepeatDuration) GetDurationInMonths() int64 {
	if o == nil {
		return 0
	}
	return o.DurationInMonths
}

func (o *CheckoutDiscountFixedRepeatDuration) GetType() DiscountType {
	if o == nil {
		return DiscountType("")
	}
	return o.Type
}

func (o *CheckoutDiscountFixedRepeatDuration) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *CheckoutDiscountFixedRepeatDuration) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *CheckoutDiscountFixedRepeatDuration) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CheckoutDiscountFixedRepeatDuration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CheckoutDiscountFixedRepeatDuration) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}
