// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CheckoutUpdatePublicCustomFieldData struct {
}

// CheckoutUpdatePublic - Update an existing checkout session using the client secret.
type CheckoutUpdatePublic struct {
	// Key-value object storing custom field values.
	CustomFieldData *CheckoutUpdatePublicCustomFieldData `json:"custom_field_data,omitempty"`
	// ID of the product price to checkout. Must correspond to a price linked to the same product.
	ProductPriceID         *string  `json:"product_price_id,omitempty"`
	Amount                 *int64   `json:"amount,omitempty"`
	CustomerName           *string  `json:"customer_name,omitempty"`
	CustomerEmail          *string  `json:"customer_email,omitempty"`
	CustomerBillingAddress *Address `json:"customer_billing_address,omitempty"`
	CustomerTaxID          *string  `json:"customer_tax_id,omitempty"`
	// Discount code to apply to the checkout.
	DiscountCode *string `json:"discount_code,omitempty"`
}

func (o *CheckoutUpdatePublic) GetCustomFieldData() *CheckoutUpdatePublicCustomFieldData {
	if o == nil {
		return nil
	}
	return o.CustomFieldData
}

func (o *CheckoutUpdatePublic) GetProductPriceID() *string {
	if o == nil {
		return nil
	}
	return o.ProductPriceID
}

func (o *CheckoutUpdatePublic) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CheckoutUpdatePublic) GetCustomerName() *string {
	if o == nil {
		return nil
	}
	return o.CustomerName
}

func (o *CheckoutUpdatePublic) GetCustomerEmail() *string {
	if o == nil {
		return nil
	}
	return o.CustomerEmail
}

func (o *CheckoutUpdatePublic) GetCustomerBillingAddress() *Address {
	if o == nil {
		return nil
	}
	return o.CustomerBillingAddress
}

func (o *CheckoutUpdatePublic) GetCustomerTaxID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerTaxID
}

func (o *CheckoutUpdatePublic) GetDiscountCode() *string {
	if o == nil {
		return nil
	}
	return o.DiscountCode
}
