// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CheckoutLegacyCreate struct {
	// ID of the product price to subscribe to.
	ProductPriceID string `json:"product_price_id"`
	// URL where the customer will be redirected after a successful subscription. You can add the `session_id={CHECKOUT_SESSION_ID}` query parameter to retrieve the checkout session id.
	SuccessURL string `json:"success_url"`
	// If you already know the email of your customer, you can set it. It'll be pre-filled on the checkout page.
	CustomerEmail *string `json:"customer_email,omitempty"`
	// ID of the subscription to update. If not provided, a new subscription will be created.
	SubscriptionID *string `json:"subscription_id,omitempty"`
}

func (o *CheckoutLegacyCreate) GetProductPriceID() string {
	if o == nil {
		return ""
	}
	return o.ProductPriceID
}

func (o *CheckoutLegacyCreate) GetSuccessURL() string {
	if o == nil {
		return ""
	}
	return o.SuccessURL
}

func (o *CheckoutLegacyCreate) GetCustomerEmail() *string {
	if o == nil {
		return nil
	}
	return o.CustomerEmail
}

func (o *CheckoutLegacyCreate) GetSubscriptionID() *string {
	if o == nil {
		return nil
	}
	return o.SubscriptionID
}
