// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CurrencyAmount struct {
	// Three letter currency code (eg: USD)
	Currency string `json:"currency"`
	// Amount in the currencies smallest unit (cents if currency is USD)
	Amount int64 `json:"amount"`
}

func (o *CurrencyAmount) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *CurrencyAmount) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}
