// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomerBenefitGrantDiscordPropertiesUpdate struct {
	AccountID string `json:"account_id"`
}

func (o *CustomerBenefitGrantDiscordPropertiesUpdate) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}
