// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomerSubscriptionUpdate struct {
	ProductPriceID string `json:"product_price_id"`
}

func (o *CustomerSubscriptionUpdate) GetProductPriceID() string {
	if o == nil {
		return ""
	}
	return o.ProductPriceID
}
