// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomFieldSelectProperties struct {
	FormLabel       *string                   `json:"form_label,omitempty"`
	FormHelpText    *string                   `json:"form_help_text,omitempty"`
	FormPlaceholder *string                   `json:"form_placeholder,omitempty"`
	Options         []CustomFieldSelectOption `json:"options"`
}

func (o *CustomFieldSelectProperties) GetFormLabel() *string {
	if o == nil {
		return nil
	}
	return o.FormLabel
}

func (o *CustomFieldSelectProperties) GetFormHelpText() *string {
	if o == nil {
		return nil
	}
	return o.FormHelpText
}

func (o *CustomFieldSelectProperties) GetFormPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.FormPlaceholder
}

func (o *CustomFieldSelectProperties) GetOptions() []CustomFieldSelectOption {
	if o == nil {
		return []CustomFieldSelectOption{}
	}
	return o.Options
}
