// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomFieldNumberProperties struct {
	FormLabel       *string `json:"form_label,omitempty"`
	FormHelpText    *string `json:"form_help_text,omitempty"`
	FormPlaceholder *string `json:"form_placeholder,omitempty"`
	Ge              *int64  `json:"ge,omitempty"`
	Le              *int64  `json:"le,omitempty"`
}

func (o *CustomFieldNumberProperties) GetFormLabel() *string {
	if o == nil {
		return nil
	}
	return o.FormLabel
}

func (o *CustomFieldNumberProperties) GetFormHelpText() *string {
	if o == nil {
		return nil
	}
	return o.FormHelpText
}

func (o *CustomFieldNumberProperties) GetFormPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.FormPlaceholder
}

func (o *CustomFieldNumberProperties) GetGe() *int64 {
	if o == nil {
		return nil
	}
	return o.Ge
}

func (o *CustomFieldNumberProperties) GetLe() *int64 {
	if o == nil {
		return nil
	}
	return o.Le
}
