// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CustomerOrderInvoice - Order's invoice data.
type CustomerOrderInvoice struct {
	// The URL to the invoice.
	URL string `json:"url"`
}

func (o *CustomerOrderInvoice) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
