// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomFieldSelectOption struct {
	Value string `json:"value"`
	Label string `json:"label"`
}

func (o *CustomFieldSelectOption) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *CustomFieldSelectOption) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}
