// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CustomerMetadataType string

const (
	CustomerMetadataTypeStr     CustomerMetadataType = "str"
	CustomerMetadataTypeInteger CustomerMetadataType = "integer"
	CustomerMetadataTypeBoolean CustomerMetadataType = "boolean"
)

type CustomerMetadata struct {
	Str     *string `queryParam:"inline"`
	Integer *int64  `queryParam:"inline"`
	Boolean *bool   `queryParam:"inline"`

	Type CustomerMetadataType
}

func CreateCustomerMetadataStr(str string) CustomerMetadata {
	typ := CustomerMetadataTypeStr

	return CustomerMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomerMetadataInteger(integer int64) CustomerMetadata {
	typ := CustomerMetadataTypeInteger

	return CustomerMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCustomerMetadataBoolean(boolean bool) CustomerMetadata {
	typ := CustomerMetadataTypeBoolean

	return CustomerMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CustomerMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = CustomerMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, true); err == nil {
		u.Integer = &integer
		u.Type = CustomerMetadataTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = &boolean
		u.Type = CustomerMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerMetadata", string(data))
}

func (u CustomerMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerMetadata: all fields are null")
}

type CustomerTaxIDType string

const (
	CustomerTaxIDTypeStr         CustomerTaxIDType = "str"
	CustomerTaxIDTypeTaxIDFormat CustomerTaxIDType = "TaxIDFormat"
)

type CustomerTaxID struct {
	Str         *string      `queryParam:"inline"`
	TaxIDFormat *TaxIDFormat `queryParam:"inline"`

	Type CustomerTaxIDType
}

func CreateCustomerTaxIDStr(str string) CustomerTaxID {
	typ := CustomerTaxIDTypeStr

	return CustomerTaxID{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomerTaxIDTaxIDFormat(taxIDFormat TaxIDFormat) CustomerTaxID {
	typ := CustomerTaxIDTypeTaxIDFormat

	return CustomerTaxID{
		TaxIDFormat: &taxIDFormat,
		Type:        typ,
	}
}

func (u *CustomerTaxID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = CustomerTaxIDTypeStr
		return nil
	}

	var taxIDFormat TaxIDFormat = TaxIDFormat("")
	if err := utils.UnmarshalJSON(data, &taxIDFormat, "", true, true); err == nil {
		u.TaxIDFormat = &taxIDFormat
		u.Type = CustomerTaxIDTypeTaxIDFormat
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerTaxID", string(data))
}

func (u CustomerTaxID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.TaxIDFormat != nil {
		return utils.MarshalJSON(u.TaxIDFormat, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerTaxID: all fields are null")
}

// Customer - A customer in an organization.
type Customer struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID             string                      `json:"id"`
	Metadata       map[string]CustomerMetadata `json:"metadata"`
	Email          string                      `json:"email"`
	EmailVerified  bool                        `json:"email_verified"`
	Name           *string                     `json:"name"`
	BillingAddress *Address                    `json:"billing_address"`
	TaxID          []CustomerTaxID             `json:"tax_id"`
	OrganizationID string                      `json:"organization_id"`
	AvatarURL      string                      `json:"avatar_url"`
}

func (c Customer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Customer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Customer) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Customer) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *Customer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Customer) GetMetadata() map[string]CustomerMetadata {
	if o == nil {
		return map[string]CustomerMetadata{}
	}
	return o.Metadata
}

func (o *Customer) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *Customer) GetEmailVerified() bool {
	if o == nil {
		return false
	}
	return o.EmailVerified
}

func (o *Customer) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Customer) GetBillingAddress() *Address {
	if o == nil {
		return nil
	}
	return o.BillingAddress
}

func (o *Customer) GetTaxID() []CustomerTaxID {
	if o == nil {
		return nil
	}
	return o.TaxID
}

func (o *Customer) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *Customer) GetAvatarURL() string {
	if o == nil {
		return ""
	}
	return o.AvatarURL
}
