// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomerBenefitGrantGitHubRepositoryPropertiesUpdate struct {
	AccountID string `json:"account_id"`
}

func (o *CustomerBenefitGrantGitHubRepositoryPropertiesUpdate) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}
