// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomerPortalOAuthAccount struct {
	AccountID       string  `json:"account_id"`
	AccountUsername *string `json:"account_username"`
}

func (o *CustomerPortalOAuthAccount) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *CustomerPortalOAuthAccount) GetAccountUsername() *string {
	if o == nil {
		return nil
	}
	return o.AccountUsername
}
