// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomFieldCheckboxProperties struct {
	FormLabel       *string `json:"form_label,omitempty"`
	FormHelpText    *string `json:"form_help_text,omitempty"`
	FormPlaceholder *string `json:"form_placeholder,omitempty"`
}

func (o *CustomFieldCheckboxProperties) GetFormLabel() *string {
	if o == nil {
		return nil
	}
	return o.FormLabel
}

func (o *CustomFieldCheckboxProperties) GetFormHelpText() *string {
	if o == nil {
		return nil
	}
	return o.FormHelpText
}

func (o *CustomFieldCheckboxProperties) GetFormPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.FormPlaceholder
}
