// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DownloadableRead struct {
	ID        string       `json:"id"`
	BenefitID string       `json:"benefit_id"`
	File      FileDownload `json:"file"`
}

func (o *DownloadableRead) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DownloadableRead) GetBenefitID() string {
	if o == nil {
		return ""
	}
	return o.BenefitID
}

func (o *DownloadableRead) GetFile() FileDownload {
	if o == nil {
		return FileDownload{}
	}
	return o.File
}
