// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ExistingProductPrice - A price that already exists for this product.
//
// Useful when updating a product if you want to keep an existing price.
type ExistingProductPrice struct {
	ID string `json:"id"`
}

func (o *ExistingProductPrice) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
