// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ExternalOrganizationSortProperty string

const (
	ExternalOrganizationSortPropertyCreatedAt      ExternalOrganizationSortProperty = "created_at"
	ExternalOrganizationSortPropertyMinusCreatedAt ExternalOrganizationSortProperty = "-created_at"
	ExternalOrganizationSortPropertyName           ExternalOrganizationSortProperty = "name"
	ExternalOrganizationSortPropertyMinusName      ExternalOrganizationSortProperty = "-name"
)

func (e ExternalOrganizationSortProperty) ToPointer() *ExternalOrganizationSortProperty {
	return &e
}
func (e *ExternalOrganizationSortProperty) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "name":
		fallthrough
	case "-name":
		*e = ExternalOrganizationSortProperty(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExternalOrganizationSortProperty: %v", v)
	}
}
