// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FilePatch struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

func (o *FilePatch) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *FilePatch) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}
