// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FileUploadCompleted struct {
	ID    string                      `json:"id"`
	Path  string                      `json:"path"`
	Parts []S3FileUploadCompletedPart `json:"parts"`
}

func (o *FileUploadCompleted) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *FileUploadCompleted) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *FileUploadCompleted) GetParts() []S3FileUploadCompletedPart {
	if o == nil {
		return []S3FileUploadCompletedPart{}
	}
	return o.Parts
}
