// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Interval string

const (
	IntervalYear  Interval = "year"
	IntervalMonth Interval = "month"
	IntervalWeek  Interval = "week"
	IntervalDay   Interval = "day"
	IntervalHour  Interval = "hour"
)

func (e Interval) ToPointer() *Interval {
	return &e
}
func (e *Interval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "year":
		fallthrough
	case "month":
		fallthrough
	case "week":
		fallthrough
	case "day":
		fallthrough
	case "hour":
		*e = Interval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Interval: %v", v)
	}
}
