// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LicenseKeyActivateConditions struct {
}

type LicenseKeyActivateMeta struct {
}

type LicenseKeyActivate struct {
	Key            string                        `json:"key"`
	OrganizationID string                        `json:"organization_id"`
	Label          string                        `json:"label"`
	Conditions     *LicenseKeyActivateConditions `json:"conditions,omitempty"`
	Meta           *LicenseKeyActivateMeta       `json:"meta,omitempty"`
}

func (o *LicenseKeyActivate) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *LicenseKeyActivate) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *LicenseKeyActivate) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *LicenseKeyActivate) GetConditions() *LicenseKeyActivateConditions {
	if o == nil {
		return nil
	}
	return o.Conditions
}

func (o *LicenseKeyActivate) GetMeta() *LicenseKeyActivateMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}
