// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LicenseKeyDeactivate struct {
	Key            string `json:"key"`
	OrganizationID string `json:"organization_id"`
	ActivationID   string `json:"activation_id"`
}

func (o *LicenseKeyDeactivate) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *LicenseKeyDeactivate) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *LicenseKeyDeactivate) GetActivationID() string {
	if o == nil {
		return ""
	}
	return o.ActivationID
}
