// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LicenseKeyUser struct {
	ID         string  `json:"id"`
	Email      string  `json:"email"`
	PublicName string  `json:"public_name"`
	AvatarURL  *string `json:"avatar_url,omitempty"`
}

func (o *LicenseKeyUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LicenseKeyUser) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *LicenseKeyUser) GetPublicName() string {
	if o == nil {
		return ""
	}
	return o.PublicName
}

func (o *LicenseKeyUser) GetAvatarURL() *string {
	if o == nil {
		return nil
	}
	return o.AvatarURL
}
