// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCustomField struct {
	Items      []CustomField `json:"items"`
	Pagination Pagination    `json:"pagination"`
}

func (o *ListResourceCustomField) GetItems() []CustomField {
	if o == nil {
		return []CustomField{}
	}
	return o.Items
}

func (o *ListResourceCustomField) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
