// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceOAuth2Client struct {
	Items      []OAuth2Client `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

func (o *ListResourceOAuth2Client) GetItems() []OAuth2Client {
	if o == nil {
		return []OAuth2Client{}
	}
	return o.Items
}

func (o *ListResourceOAuth2Client) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
