// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCheckout struct {
	Items      []Checkout `json:"items"`
	Pagination Pagination `json:"pagination"`
}

func (o *ListResourceCheckout) GetItems() []Checkout {
	if o == nil {
		return []Checkout{}
	}
	return o.Items
}

func (o *ListResourceCheckout) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
