// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCustomerSubscription struct {
	Items      []CustomerSubscription `json:"items"`
	Pagination Pagination             `json:"pagination"`
}

func (o *ListResourceCustomerSubscription) GetItems() []CustomerSubscription {
	if o == nil {
		return []CustomerSubscription{}
	}
	return o.Items
}

func (o *ListResourceCustomerSubscription) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
