// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceOrganization struct {
	Items      []Organization `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

func (o *ListResourceOrganization) GetItems() []Organization {
	if o == nil {
		return []Organization{}
	}
	return o.Items
}

func (o *ListResourceOrganization) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
