// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceOrder struct {
	Items      []Order    `json:"items"`
	Pagination Pagination `json:"pagination"`
}

func (o *ListResourceOrder) GetItems() []Order {
	if o == nil {
		return []Order{}
	}
	return o.Items
}

func (o *ListResourceOrder) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
