// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceSubscription struct {
	Items      []Subscription `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

func (o *ListResourceSubscription) GetItems() []Subscription {
	if o == nil {
		return []Subscription{}
	}
	return o.Items
}

func (o *ListResourceSubscription) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
