// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCustomerOrder struct {
	Items      []CustomerOrder `json:"items"`
	Pagination Pagination      `json:"pagination"`
}

func (o *ListResourceCustomerOrder) GetItems() []CustomerOrder {
	if o == nil {
		return []CustomerOrder{}
	}
	return o.Items
}

func (o *ListResourceCustomerOrder) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
