// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceExternalOrganization struct {
	Items      []ExternalOrganization `json:"items"`
	Pagination Pagination             `json:"pagination"`
}

func (o *ListResourceExternalOrganization) GetItems() []ExternalOrganization {
	if o == nil {
		return []ExternalOrganization{}
	}
	return o.Items
}

func (o *ListResourceExternalOrganization) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
