// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCheckoutLink struct {
	Items      []CheckoutLink `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

func (o *ListResourceCheckoutLink) GetItems() []CheckoutLink {
	if o == nil {
		return []CheckoutLink{}
	}
	return o.Items
}

func (o *ListResourceCheckoutLink) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
