// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceLicenseKeyRead struct {
	Items      []LicenseKeyRead `json:"items"`
	Pagination Pagination       `json:"pagination"`
}

func (o *ListResourceLicenseKeyRead) GetItems() []LicenseKeyRead {
	if o == nil {
		return []LicenseKeyRead{}
	}
	return o.Items
}

func (o *ListResourceLicenseKeyRead) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
