// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceDownloadableRead struct {
	Items      []DownloadableRead `json:"items"`
	Pagination Pagination         `json:"pagination"`
}

func (o *ListResourceDownloadableRead) GetItems() []DownloadableRead {
	if o == nil {
		return []DownloadableRead{}
	}
	return o.Items
}

func (o *ListResourceDownloadableRead) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
