// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceDiscount struct {
	Items      []Discount `json:"items"`
	Pagination Pagination `json:"pagination"`
}

func (o *ListResourceDiscount) GetItems() []Discount {
	if o == nil {
		return []Discount{}
	}
	return o.Items
}

func (o *ListResourceDiscount) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
