// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceBenefit struct {
	Items      []Benefit  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

func (o *ListResourceBenefit) GetItems() []Benefit {
	if o == nil {
		return []Benefit{}
	}
	return o.Items
}

func (o *ListResourceBenefit) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
