// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCustomer struct {
	Items      []Customer `json:"items"`
	Pagination Pagination `json:"pagination"`
}

func (o *ListResourceCustomer) GetItems() []Customer {
	if o == nil {
		return []Customer{}
	}
	return o.Items
}

func (o *ListResourceCustomer) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
