// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceBenefitGrant struct {
	Items      []BenefitGrant `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

func (o *ListResourceBenefitGrant) GetItems() []BenefitGrant {
	if o == nil {
		return []BenefitGrant{}
	}
	return o.Items
}

func (o *ListResourceBenefitGrant) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}
