// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetricsResponse - Metrics response schema.
type MetricsResponse struct {
	// List of data for each timestamp.
	Periods []MetricPeriod `json:"periods"`
	Metrics Metrics        `json:"metrics"`
}

func (o *MetricsResponse) GetPeriods() []MetricPeriod {
	if o == nil {
		return []MetricPeriod{}
	}
	return o.Periods
}

func (o *MetricsResponse) GetMetrics() Metrics {
	if o == nil {
		return Metrics{}
	}
	return o.Metrics
}
