// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetricsIntervalLimit - Date interval limit to get metrics for a given interval.
type MetricsIntervalLimit struct {
	// Maximum number of days for this interval.
	MaxDays int64 `json:"max_days"`
}

func (o *MetricsIntervalLimit) GetMaxDays() int64 {
	if o == nil {
		return 0
	}
	return o.MaxDays
}
