// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetricsIntervalsLimits - Date interval limits to get metrics for each interval.
type MetricsIntervalsLimits struct {
	// Date interval limit to get metrics for a given interval.
	Hour MetricsIntervalLimit `json:"hour"`
	// Date interval limit to get metrics for a given interval.
	Day MetricsIntervalLimit `json:"day"`
	// Date interval limit to get metrics for a given interval.
	Week MetricsIntervalLimit `json:"week"`
	// Date interval limit to get metrics for a given interval.
	Month MetricsIntervalLimit `json:"month"`
	// Date interval limit to get metrics for a given interval.
	Year MetricsIntervalLimit `json:"year"`
}

func (o *MetricsIntervalsLimits) GetHour() MetricsIntervalLimit {
	if o == nil {
		return MetricsIntervalLimit{}
	}
	return o.Hour
}

func (o *MetricsIntervalsLimits) GetDay() MetricsIntervalLimit {
	if o == nil {
		return MetricsIntervalLimit{}
	}
	return o.Day
}

func (o *MetricsIntervalsLimits) GetWeek() MetricsIntervalLimit {
	if o == nil {
		return MetricsIntervalLimit{}
	}
	return o.Week
}

func (o *MetricsIntervalsLimits) GetMonth() MetricsIntervalLimit {
	if o == nil {
		return MetricsIntervalLimit{}
	}
	return o.Month
}

func (o *MetricsIntervalsLimits) GetYear() MetricsIntervalLimit {
	if o == nil {
		return MetricsIntervalLimit{}
	}
	return o.Year
}
