// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Metric - Information about a metric.
type Metric struct {
	// Unique identifier for the metric.
	Slug string `json:"slug"`
	// Human-readable name for the metric.
	DisplayName string     `json:"display_name"`
	Type        MetricType `json:"type"`
}

func (o *Metric) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *Metric) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *Metric) GetType() MetricType {
	if o == nil {
		return MetricType("")
	}
	return o.Type
}
