// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrganizationProfileSettings struct {
	// If this organization has a profile enabled
	Enabled *bool `json:"enabled,omitempty"`
	// A description of the organization
	Description *string `json:"description,omitempty"`
	// A list of featured projects
	FeaturedProjects []string `json:"featured_projects,omitempty"`
	// A list of featured organizations
	FeaturedOrganizations []string `json:"featured_organizations,omitempty"`
	// A list of links associated with the organization
	Links []string `json:"links,omitempty"`
	// Subscription promotion settings
	Subscribe *OrganizationSubscribePromoteSettings `json:"subscribe,omitempty"`
	// Accent color for the organization
	AccentColor *string `json:"accent_color,omitempty"`
}

func (o *OrganizationProfileSettings) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *OrganizationProfileSettings) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrganizationProfileSettings) GetFeaturedProjects() []string {
	if o == nil {
		return nil
	}
	return o.FeaturedProjects
}

func (o *OrganizationProfileSettings) GetFeaturedOrganizations() []string {
	if o == nil {
		return nil
	}
	return o.FeaturedOrganizations
}

func (o *OrganizationProfileSettings) GetLinks() []string {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *OrganizationProfileSettings) GetSubscribe() *OrganizationSubscribePromoteSettings {
	if o == nil {
		return nil
	}
	return o.Subscribe
}

func (o *OrganizationProfileSettings) GetAccentColor() *string {
	if o == nil {
		return nil
	}
	return o.AccentColor
}
