// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Pagination struct {
	TotalCount int64 `json:"total_count"`
	MaxPage    int64 `json:"max_page"`
}

func (o *Pagination) GetTotalCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalCount
}

func (o *Pagination) GetMaxPage() int64 {
	if o == nil {
		return 0
	}
	return o.MaxPage
}
