// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Platforms string

const (
	PlatformsGithub Platforms = "github"
)

func (e Platforms) ToPointer() *Platforms {
	return &e
}
func (e *Platforms) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "github":
		*e = Platforms(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Platforms: %v", v)
	}
}
