// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Pledger struct {
	Name           string  `json:"name"`
	GithubUsername *string `json:"github_username"`
	AvatarURL      *string `json:"avatar_url"`
}

func (o *Pledger) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Pledger) GetGithubUsername() *string {
	if o == nil {
		return nil
	}
	return o.GithubUsername
}

func (o *Pledger) GetAvatarURL() *string {
	if o == nil {
		return nil
	}
	return o.AvatarURL
}
