// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PledgeType string

const (
	PledgeTypePayUpfront      PledgeType = "pay_upfront"
	PledgeTypePayOnCompletion PledgeType = "pay_on_completion"
	PledgeTypePayDirectly     PledgeType = "pay_directly"
)

func (e PledgeType) ToPointer() *PledgeType {
	return &e
}
func (e *PledgeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pay_upfront":
		fallthrough
	case "pay_on_completion":
		fallthrough
	case "pay_directly":
		*e = PledgeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PledgeType: %v", v)
	}
}
