// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ProductPriceType string

const (
	ProductPriceTypeOneTime   ProductPriceType = "one_time"
	ProductPriceTypeRecurring ProductPriceType = "recurring"
)

func (e ProductPriceType) ToPointer() *ProductPriceType {
	return &e
}
func (e *ProductPriceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "one_time":
		fallthrough
	case "recurring":
		*e = ProductPriceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductPriceType: %v", v)
	}
}
