// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProductBenefitsUpdate - Schema to update the benefits granted by a product.
type ProductBenefitsUpdate struct {
	// List of benefit IDs. Each one must be on the same organization as the product.
	Benefits []string `json:"benefits"`
}

func (o *ProductBenefitsUpdate) GetBenefits() []string {
	if o == nil {
		return []string{}
	}
	return o.Benefits
}
