// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Reactions struct {
	TotalCount int64 `json:"total_count"`
	PlusOne    int64 `json:"plus_one"`
	MinusOne   int64 `json:"minus_one"`
	Laugh      int64 `json:"laugh"`
	Hooray     int64 `json:"hooray"`
	Confused   int64 `json:"confused"`
	Heart      int64 `json:"heart"`
	Rocket     int64 `json:"rocket"`
	Eyes       int64 `json:"eyes"`
}

func (o *Reactions) GetTotalCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalCount
}

func (o *Reactions) GetPlusOne() int64 {
	if o == nil {
		return 0
	}
	return o.PlusOne
}

func (o *Reactions) GetMinusOne() int64 {
	if o == nil {
		return 0
	}
	return o.MinusOne
}

func (o *Reactions) GetLaugh() int64 {
	if o == nil {
		return 0
	}
	return o.Laugh
}

func (o *Reactions) GetHooray() int64 {
	if o == nil {
		return 0
	}
	return o.Hooray
}

func (o *Reactions) GetConfused() int64 {
	if o == nil {
		return 0
	}
	return o.Confused
}

func (o *Reactions) GetHeart() int64 {
	if o == nil {
		return 0
	}
	return o.Heart
}

func (o *Reactions) GetRocket() int64 {
	if o == nil {
		return 0
	}
	return o.Rocket
}

func (o *Reactions) GetEyes() int64 {
	if o == nil {
		return 0
	}
	return o.Eyes
}
