// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RepositoryProfileSettings struct {
	// A description of the repository
	Description *string `json:"description,omitempty"`
	// A URL to a cover image
	CoverImageURL *string `json:"cover_image_url,omitempty"`
	// A list of featured organizations
	FeaturedOrganizations []string `json:"featured_organizations,omitempty"`
	// A list of highlighted subscription tiers
	HighlightedSubscriptionTiers []string `json:"highlighted_subscription_tiers,omitempty"`
	// A list of links related to the repository
	Links []string `json:"links,omitempty"`
}

func (o *RepositoryProfileSettings) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RepositoryProfileSettings) GetCoverImageURL() *string {
	if o == nil {
		return nil
	}
	return o.CoverImageURL
}

func (o *RepositoryProfileSettings) GetFeaturedOrganizations() []string {
	if o == nil {
		return nil
	}
	return o.FeaturedOrganizations
}

func (o *RepositoryProfileSettings) GetHighlightedSubscriptionTiers() []string {
	if o == nil {
		return nil
	}
	return o.HighlightedSubscriptionTiers
}

func (o *RepositoryProfileSettings) GetLinks() []string {
	if o == nil {
		return nil
	}
	return o.Links
}
