// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RepositoryUpdate struct {
	ProfileSettings *RepositoryProfileSettingsUpdate `json:"profile_settings,omitempty"`
}

func (o *RepositoryUpdate) GetProfileSettings() *RepositoryProfileSettingsUpdate {
	if o == nil {
		return nil
	}
	return o.ProfileSettings
}
