// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RepositoryProfileSettingsUpdate struct {
	SetDescription               *bool    `json:"set_description,omitempty"`
	Description                  *string  `json:"description,omitempty"`
	SetCoverImageURL             *bool    `json:"set_cover_image_url,omitempty"`
	CoverImageURL                *string  `json:"cover_image_url,omitempty"`
	FeaturedOrganizations        []string `json:"featured_organizations,omitempty"`
	HighlightedSubscriptionTiers []string `json:"highlighted_subscription_tiers,omitempty"`
	Links                        []string `json:"links,omitempty"`
}

func (o *RepositoryProfileSettingsUpdate) GetSetDescription() *bool {
	if o == nil {
		return nil
	}
	return o.SetDescription
}

func (o *RepositoryProfileSettingsUpdate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RepositoryProfileSettingsUpdate) GetSetCoverImageURL() *bool {
	if o == nil {
		return nil
	}
	return o.SetCoverImageURL
}

func (o *RepositoryProfileSettingsUpdate) GetCoverImageURL() *string {
	if o == nil {
		return nil
	}
	return o.CoverImageURL
}

func (o *RepositoryProfileSettingsUpdate) GetFeaturedOrganizations() []string {
	if o == nil {
		return nil
	}
	return o.FeaturedOrganizations
}

func (o *RepositoryProfileSettingsUpdate) GetHighlightedSubscriptionTiers() []string {
	if o == nil {
		return nil
	}
	return o.HighlightedSubscriptionTiers
}

func (o *RepositoryProfileSettingsUpdate) GetLinks() []string {
	if o == nil {
		return nil
	}
	return o.Links
}
