// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type S3FileUploadCompletedPart struct {
	Number               int64   `json:"number"`
	ChecksumEtag         string  `json:"checksum_etag"`
	ChecksumSha256Base64 *string `json:"checksum_sha256_base64"`
}

func (o *S3FileUploadCompletedPart) GetNumber() int64 {
	if o == nil {
		return 0
	}
	return o.Number
}

func (o *S3FileUploadCompletedPart) GetChecksumEtag() string {
	if o == nil {
		return ""
	}
	return o.ChecksumEtag
}

func (o *S3FileUploadCompletedPart) GetChecksumSha256Base64() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha256Base64
}
