// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type S3FileUploadMultipart struct {
	ID    string             `json:"id"`
	Path  string             `json:"path"`
	Parts []S3FileUploadPart `json:"parts"`
}

func (o *S3FileUploadMultipart) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *S3FileUploadMultipart) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *S3FileUploadMultipart) GetParts() []S3FileUploadPart {
	if o == nil {
		return []S3FileUploadPart{}
	}
	return o.Parts
}
