// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type S3FileCreateMultipart struct {
	Parts []S3FileCreatePart `json:"parts"`
}

func (o *S3FileCreateMultipart) GetParts() []S3FileCreatePart {
	if o == nil {
		return []S3FileCreatePart{}
	}
	return o.Parts
}
