// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type S3FileCreatePart struct {
	Number               int64   `json:"number"`
	ChunkStart           int64   `json:"chunk_start"`
	ChunkEnd             int64   `json:"chunk_end"`
	ChecksumSha256Base64 *string `json:"checksum_sha256_base64,omitempty"`
}

func (o *S3FileCreatePart) GetNumber() int64 {
	if o == nil {
		return 0
	}
	return o.Number
}

func (o *S3FileCreatePart) GetChunkStart() int64 {
	if o == nil {
		return 0
	}
	return o.ChunkStart
}

func (o *S3FileCreatePart) GetChunkEnd() int64 {
	if o == nil {
		return 0
	}
	return o.ChunkEnd
}

func (o *S3FileCreatePart) GetChecksumSha256Base64() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha256Base64
}
