// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	AccessToken *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=polar_access_token"`
}

func (o *Security) GetAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.AccessToken
}
