// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SubscriptionRecurringInterval string

const (
	SubscriptionRecurringIntervalMonth SubscriptionRecurringInterval = "month"
	SubscriptionRecurringIntervalYear  SubscriptionRecurringInterval = "year"
)

func (e SubscriptionRecurringInterval) ToPointer() *SubscriptionRecurringInterval {
	return &e
}
func (e *SubscriptionRecurringInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "month":
		fallthrough
	case "year":
		*e = SubscriptionRecurringInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionRecurringInterval: %v", v)
	}
}
