// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubscriptionUser struct {
	ID             string  `json:"id"`
	Email          string  `json:"email"`
	PublicName     string  `json:"public_name"`
	AvatarURL      *string `json:"avatar_url,omitempty"`
	GithubUsername *string `json:"github_username,omitempty"`
}

func (o *SubscriptionUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SubscriptionUser) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *SubscriptionUser) GetPublicName() string {
	if o == nil {
		return ""
	}
	return o.PublicName
}

func (o *SubscriptionUser) GetAvatarURL() *string {
	if o == nil {
		return nil
	}
	return o.AvatarURL
}

func (o *SubscriptionUser) GetGithubUsername() *string {
	if o == nil {
		return nil
	}
	return o.GithubUsername
}
