// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserInfoOrganization struct {
	Sub  string  `json:"sub"`
	Name *string `json:"name,omitempty"`
}

func (o *UserInfoOrganization) GetSub() string {
	if o == nil {
		return ""
	}
	return o.Sub
}

func (o *UserInfoOrganization) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
